services:
  db:
    image: mysql
    restart: always
    ports:
      - "9190:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: user_authentication